### ISSUE TITLE
Module dsp has no attribute google

### ISSUE THREAD

**Issue by aparnajore** [stanfordnlp/dspy#417]
I am trying to use Google LM but getting error that module dsp has no attribute google.

**Comment by KCaverly** [comment]
Fixed with #419, for now, you can directly import it with dsp.modules.google import Google.

**Comment by aparnajore** [comment]
Still facing issues like google_api_error is not defined and api_key is not an attribute of Google class.

**Comment by KCaverly** [comment]
Thanks @aparnajore, for following up, those have been wrapped up in the PR

**Comment by aparnajore** [comment]
Hello @KCaverly, 
Thanks for the update.

**Comment by shishanksid** [comment]
@KCaverly Do we have any update on the above concern?

**Comment by okhat** [comment]
This is now merged into main. Will be in the pypi release too.

**Comment by aparnajore** [comment]
Hello @KCaverly, facing some new issues while working with Google LM like:
AttributeError: 'Google' object has no attribute 'co'
During handling of the above exception, another exception occurred:
AttributeError: 'AttributeError' object has no attribute 'message'

**Comment by ashwin-sid** [comment]
Still getting similar error - 
`AttributeError: module 'dspy' has no attribute 'Google'`

**Environment** - Google Colab; DSPY 3.0.3
