### ISSUE TITLE
[Bug] user message formatting is inconsistent with adapter

### ISSUE THREAD

**Issue by BenMcH** [stanfordnlp/dspy#9002]
### What happened?

Given that most adapters inherit from the chat adapter, it seems as though there are different expectations that are inherited within each new adapter that are not being properly formatted, specifically with user messages.

Chat Adapter (Consistent):

<img width="1350" height="703" alt="Image" src="https://github.com/user-attachments/assets/99796382-6ec8-476c-a874-741d6854c2d6" />

JSON Adapter (Different formatting between user & assistant messages, but seems to be intentional):

<img width="1336" height="696" alt="Image" src="https://github.com/user-attachments/assets/4216bdb2-f209-48d6-9050-7387e42d600c" />

XML Adapter - Different input than is described + provides contradictory "completed" instructions (`<completed>` vs `[[ ## completed ## ]]`):

<img width="1362" height="709" alt="Image" src="https://github.com/user-attachments/assets/0a611232-9cd1-4461-b06c-24d2f5646e27" />

### Steps to reproduce

Setup tracing with your tool of choice (I used arize phoenix, you can also use mlflow or `.inspect_history()`) and see the inputs/outputs

### DSPy version

3.0.3

**Comment by TomeHirata** [comment]
Can you try 3.0.4b2? I think this issue has been addressed in https://github.com/stanfordnlp/dspy/pull/8876

**Comment by BenMcH** [comment]
> Can you try 3.0.4b2? I think this issue has been addressed in https://github.com/stanfordnlp/dspy/pull/8876

The small PR I posted (#9003) fixes the issue 🙂 that PR still uses the bracketed syntax for user messages. I confirmed the issue still exists on main before starting work on the pull request.
